### ISSUE TITLE
fdt_strerror missing FDT alignment error in 1.6.1

### ISSUE THREAD

**Issue by kallisti5** [dgibson/dtc#56] opened 2021-11-05 23:14 UTC
Getting "unknown error"...
```
fdt_register_node ERROR: fdt_get_name -19 - <unknown error>
```

FDT_ERR_ALIGNMENT seems to be missing in fdt_strerror in 1.6.1.

Any chance of a 1.6.2 version?   :-)

**Comment by dgibson** [comment] 2021-11-08 05:15
> Any chance of a 1.6.2 version? :-)

Uh.. sure?  I just need to find time to do it.

**Comment by dgibson** [comment] 2023-02-02 06:26
Closing, since remaining issue is a duplicate of #75

**Closed by dgibson** 2023-02-02 06:26 UTC
